<?php
add_action('acf/include_fields', function () {
	if (!function_exists('acf_add_local_field_group')) {
		return;
	}

	acf_add_local_field_group(array(
		'key' => 'group_666006d52a9c0',
		'title' => 'Modules List',
		'fields' => array(
			array(
				'key' => 'field_666006d561672',
				'label' => 'Modules',
				'name' => 'modules',
				'aria-label' => '',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout_66a4ebd1ca8c3' => array(
					'key' => 'layout_66a4ebd1ca8c3',
					'name' => 'select_plannings',
					'label' => 'Select plannings',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_66a4ebe6ca8c5',
							'label' => 'Select plannings',
							'name' => 'select_plannings',
							'aria-label' => '',
							'type' => 'relationship',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'plannings',
							),
							'post_status' => '',
							'taxonomy' => '',
							'filters' => array(
								0 => 'search',
								1 => 'post_type',
								2 => 'taxonomy',
							),
							'return_format' => 'object',
							'min' => '',
							'max' => '',
							'elements' => '',
							'bidirectional' => 0,
							'bidirectional_target' => array(
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layouts' => array (
					'layout_66680824e3abd' => array(
						'key' => 'layout_66680824e3abd',
						'name' => 'banner_module',
						'label' => 'Banner Module',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_66680838e3abf',
								'label' => 'Image Block',
								'name' => 'image_block',
								'aria-label' => '',
								'type' => 'image',
								'instructions' => 'In this section you can add pictures for modules.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
								'preview_size' => 'medium',
							),
							array(
								'key' => 'field_66684604c0cca',
								'label' => 'Title',
								'name' => 'title',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => 'In this section you can add title for modules.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
							),
							array(
								'key' => 'field_66684621c0ccb',
								'label' => 'Description',
								'name' => 'description',
								'aria-label' => '',
								'type' => 'textarea',
								'instructions' => 'In this section you can add a description of modules.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'rows' => '',
								'placeholder' => '',
								'new_lines' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_66a4ebd1ca8c3' => array(
					'key' => 'layout_66a4ebd1ca8c3',
					'name' => 'select_plannings',
					'label' => 'Select plannings',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_66a4ebe6ca8c5',
							'label' => 'Select plannings',
							'name' => 'select_plannings',
							'aria-label' => '',
							'type' => 'relationship',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'plannings',
							),
							'post_status' => '',
							'taxonomy' => '',
							'filters' => array(
								0 => 'search',
								1 => 'post_type',
								2 => 'taxonomy',
							),
							'return_format' => 'object',
							'min' => '',
							'max' => '',
							'elements' => '',
							'bidirectional' => 0,
							'bidirectional_target' => array(
							),
						),
					),
					'min' => '',
					'max' => '',
				),
					'layout_6688695f441ae' => array(
						'key' => 'layout_6688695f441ae',
						'name' => 'teams_module',
						'label' => 'Teams Module',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_66886973441b0',
								'label' => 'Teams Module',
								'name' => 'teams_module',
								'aria-label' => '',
								'type' => 'relationship',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'post_type' => array(
									0 => 'teams',
								),
								'post_status' => '',
								'taxonomy' => '',
								'filters' => array(
									0 => 'search',
									1 => 'post_type',
									2 => 'taxonomy',
								),
								'return_format' => 'object',
								'min' => '',
								'max' => '',
								'elements' => '',
								'bidirectional' => 0,
								'bidirectional_target' => array(
								),
							),
						),
						'min' => '',
						'max' => '',
					),


					'layout_6673c54e2104b' => array(
					'key' => 'layout_6673c54e2104b',
					'name' => 'faq',
					'label' => 'Faq',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6673cf525a7a7',
							'label' => 'Faq',
							'name' => 'faq',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add Row',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_6673cf6c5a7a8',
									'label' => 'Question',
									'name' => 'question',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_6673cf525a7a7',
								),
								array(
									'key' => 'field_6673cf785a7a9',
									'label' => 'Answer',
									'name' => 'answer',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
									'parent_repeater' => 'field_6673cf525a7a7',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),

				'layout_6697a178fb162' => array(
					'key' => 'layout_6697a178fb162',
					'name' => 'resources_module',
					'label' => 'Resources Module',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6697a1b0fb164',
							'label' => 'Resource Category',
							'name' => 'resource_category',
							'aria-label' => '',
							'type' => 'taxonomy',
							'instructions' => 'Select the resources category.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'resource_category',
							'add_term' => 0,
							'save_terms' => 0,
							'load_terms' => 0,
							'return_format' => 'id',
							'field_type' => 'select',
							'allow_null' => 0,
							'bidirectional' => 0,
							'multiple' => 0,
							'bidirectional_target' => array(
							),
						),
						array(
							'key' => 'field_6697a20afb165',
							'label' => 'Resource Selection Type',
							'name' => 'resource_selection_type',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => 'Choose whether to display the latest 7 resources or manually select resources.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Latest' => 'Latest',
								'Manual' => 'Manual',
							),
							'default_value' => '',
							'return_format' => 'value',
							'allow_null' => 0,
							'other_choice' => 0,
							'layout' => 'horizontal',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_6697a23efb166',
							'label' => 'Select Resources',
							'name' => 'select_resources',
							'aria-label' => '',
							'type' => 'relationship',
							'instructions' => 'Select resources.',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_6697a20afb165',
										'operator' => '==',
										'value' => 'Manual',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'resources',
							),
							'post_status' => '',
							'taxonomy' => '',
							'filters' => array(
								0 => 'taxonomy',
							),
							'return_format' => 'object',
							'min' => '',
							'max' => '',
							'elements' => '',
							'bidirectional' => 0,
							'bidirectional_target' => array(
							),
						),
					),
					'min' => '',
					'max' => '',
				),

				'layout_668da3b98a49e' => array(
					'key' => 'layout_668da3b98a49e',
					'name' => 'stats_module',
					'label' => 'Stats Module',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_668da4072801b',
							'label' => 'Stats Module',
							'name' => 'stats_module',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add Row',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_668da41a2801c',
									'label' => 'Statistic Value',
									'name' => 'statistic_value',
									'aria-label' => '',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'min' => '',
									'max' => '',
									'placeholder' => '',
									'step' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_668da4072801b',
								),
								array(
									'key' => 'field_668da4282801d',
									'label' => 'Statistic Text',
									'name' => 'statistic_text',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_668da4072801b',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_669cf37c4f9c2' => array(
					'key' => 'layout_669cf37c4f9c2',
					'name' => 'anchor_menu',
					'label' => 'Anchor Menu',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_669cf3914f9c8',
							'label' => 'Anchor Menu',
							'name' => 'anchor_menu',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
					),
					'min' => '',
					'max' => '',
				),

				
                'layout_6688695f441af' => array(
                    'key' => 'layout_6688695f441af',
                    'name' => 'infocard_module',
                    'label' => 'Infocard Module',
                    'display' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_66886973441b1',
                            'label' => 'Title',
                            'name' => 'title',
                            'type' => 'text',
                            'instructions' => 'Enter the title for the infocard.',
                            'required' => 1,
                        ),
                        array(
                            'key' => 'field_66886973441b2',
                            'label' => 'Description',
                            'name' => 'description',
                            'type' => 'textarea',
                            'instructions' => 'Enter the description for the infocard (max 2 lines).',
                            'required' => 1,
                            'maxlength' => 120,
                        ),
                        array(
                            'key' => 'field_66886973441b3',
                            'label' => 'Image',
                            'name' => 'image',
                            'type' => 'image',
                            'instructions' => 'Upload an image for the infocard.',
                            'required' => 1,
                            'return_format' => 'array',
                            'preview_size' => 'medium',
                        ),
                    ),
                ), 
				'layout_calendar_module' => array(
    'key' => 'layout_calendar_module',
    'name' => 'calendar_module',
    'label' => 'Calendar Module',
    'display' => 'block',
    'sub_fields' => array(
        array(
            'key' => 'field_calendar_module_title',
            'label' => 'Title',
            'name' => 'title',
            'type' => 'text',
            'instructions' => 'Add a title for the calendar module.',
            'required' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => 'Calendar',
        ),
        array(
            'key' => 'field_calendar_module_events',
            'label' => 'Events',
            'name' => 'events',
            'type' => 'repeater',
            'instructions' => 'Add events for the calendar.',
            'required' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => 'field_event_title',
            'min' => 0,
            'max' => 0,
            'layout' => 'block',
            'button_label' => 'Add Event',
            'sub_fields' => array(
                array(
                    'key' => 'field_event_title',
                    'label' => 'Title',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => 'Enter the event title.',
                    'required' => 1,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_event_description',
                    'label' => 'Description',
                    'name' => 'description',
                    'type' => 'textarea',
                    'instructions' => 'Enter the event description.',
                    'required' => 1,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => '',
                ),
                array(
                    'key' => 'field_event_date',
                    'label' => 'Date',
                    'name' => 'date',
                    'type' => 'date_picker',
                    'instructions' => 'Select the event date.',
                    'required' => 1,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'Y-m-d',
                    'return_format' => 'Y-m-d',
                    'first_day' => 1,
                ),
                array(
                    'key' => 'field_event_start_time',
                    'label' => 'Start Time',
                    'name' => 'start_time',
                    'type' => 'time_picker',
                    'instructions' => 'Select the event start time.',
                    'required' => 1,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i',
                    'return_format' => 'H:i',
                ),
                array(
                    'key' => 'field_event_end_time',
                    'label' => 'End Time',
                    'name' => 'end_time',
                    'type' => 'time_picker',
                    'instructions' => 'Select the event end time.',
                    'required' => 1,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i',
                    'return_format' => 'H:i',
                ),
            ),
        ),
    ),
),
            
				'layout_6672f39075b35' => array(
									'key' => 'layout_6672f39075b35',
									'name' => 'card',
									'label' => 'Card',
									'sub_fields' => array(
										array(
											'key' => 'field_selection_type',
											'label' => 'Selection Type',
											'name' => 'selection_type',
											'type' => 'radio',
											'choices' => array(
												'latest' => 'Latest',
												'manual' => 'Manual',
											),
											'default_value' => 'latest',
										),
										array(
											'key' => 'field_manual_post_type',
											'label' => 'Select Post Type',
											'name' => 'manual_post_type',
											'type' => 'button_group',
											'choices' => array(
												'post' => 'Posts',
												'teams' => 'Teams',
												'documentation' => 'Documentation',
												'products' => 'Products',
												'tech-support' => 'Tech Support',
											),
											'layout' => 'horizontal',
											'return_format' => 'value',
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_selection_type',
														'operator' => '==',
														'value' => 'manual',
													),
												),
											),
										),
										array(
											'key' => 'field_manual_posts',
											'label' => 'Manual Posts',
											'name' => 'manual_posts',
											'type' => 'relationship',
											'post_type' => array('post'), 
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_selection_type',
														'operator' => '==',
														'value' => 'manual',
													),
													array(
														'field' => 'field_manual_post_type',
														'operator' => '==',
														'value' => 'post',
													),
												),
											),
											'filters' => array(
												'search',
											),
											'elements' => array(
												'featured_image',
											),
										),
										array(
											'key' => 'field_manual_teams',
											'label' => 'Manual Teams',
											'name' => 'manual_teams',
											'type' => 'relationship',
											'post_type' => array('teams'), 
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_selection_type',
														'operator' => '==',
														'value' => 'manual',
													),
													array(
														'field' => 'field_manual_post_type',
														'operator' => '==',
														'value' => 'teams',
													),
												),
											),
											'filters' => array(
												'search',
											),
											'elements' => array(
												'featured_image',
											),
										),
										
										array(
											'key' => 'field_card_title',
											'label' => 'Card Title',
											'name' => 'card_title',
											'type' => 'text',
											'instructions' => 'Enter the title for this card section',
										),
										array(
											'key' => 'field_manual_documentation',
											'label' => 'Manual Documentation',
											'name' => 'manual_documentation',
											'type' => 'relationship',
											'post_type' => array('documentation'), 
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_selection_type',
														'operator' => '==',
														'value' => 'manual',
													),
													array(
														'field' => 'field_manual_post_type',
														'operator' => '==',
														'value' => 'documentation',
													),
												),
											),
											'filters' => array(
												'search',
											),
											'elements' => array(
												'featured_image',
											),
										),
										array(
											'key' => 'field_manual_products',
											'label' => 'Manual Products',
											'name' => 'manual_products',
											'type' => 'relationship',
											'post_type' => array('products'), 
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_selection_type',
														'operator' => '==',
														'value' => 'manual',
													),
													array(
														'field' => 'field_manual_post_type',
														'operator' => '==',
														'value' => 'products',
													),
												),
											),
											'filters' => array(
												'search',
											),
											'elements' => array(
												'featured_image',
											),
										),

										array(
											'key' => 'field_manual_support',
											'label' => 'Manual Support',
											'name' => 'manual_support',
											'type' => 'relationship',
											'post_type' => array('tech-support'), 
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_selection_type',
														'operator' => '==',
														'value' => 'manual',
													),
													array(
														'field' => 'field_manual_post_type',
														'operator' => '==',
														'value' => 'tech-support',
													),
												),
											),
											'filters' => array(
												'search',
											),
											'elements' => array(
												'featured_image',
											),
										),
									),
								),

					'layout_66741577303f8' => array(
						'key' => 'layout_66741577303f8',
						'name' => 'iframe_block',
						'label' => 'Iframe Block',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_66741591303fa',
								'label' => 'URL',
								'name' => 'url',
								'aria-label' => '',
								'type' => 'url',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_666006e451377' => array(
						'key' => 'layout_666006e451377',
						'name' => 'wysiwyg_block',
						'label' => 'WYSIWYG Content',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_6660074c61674',
								'label' => 'WYSIWYG Editor',
								'name' => 'wysiwyg_editor',
								'aria-label' => '',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
								'delay' => 0,
							),
						),
					),
				
					'layout_666006e45137b' => array(
						'key' => 'layout_666006e45137b',
						'label' => 'Search Bar',
						'name' => 'search_bar',
						'type' => 'group',
						'sub_fields' => array(
							array(
								'key' => 'field_search_input',
								'label' => 'Search Input',
								'name' => 'search_input',
								'type' => 'text',
								'instructions' => 'Enter placeholder text for the search input.',
							
						),
					),
				),

				'layout_benefits_bar' => array(
    'key' => 'layout_benefits_bar',
    'name' => 'benefits_bar',
    'label' => 'Benefits Bar',
    'display' => 'block',
    'sub_fields' => array(
        array(
            'key' => 'field_benefits_bar_title',
            'label' => 'Title',
            'name' => 'title',
            'type' => 'text',
            'instructions' => 'Enter the title for the benefits bar.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        array(
            'key' => 'field_benefits_bar_repeater',
            'label' => 'Benefits',
            'name' => 'benefits',
            'type' => 'repeater',
            'instructions' => 'Add the benefits here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'block',
            'button_label' => 'Add Benefit',
            'sub_fields' => array(
                array(
                    'key' => 'field_benefit_icon',
                    'label' => 'Icon',
                    'name' => 'icon',
                    'type' => 'image',
                    'instructions' => 'Select an icon for the benefit.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => 'svg,png',  
                ),
                array(
                    'key' => 'field_benefit_text',
                    'label' => 'Text',
                    'name' => 'text',
                    'type' => 'text',
                    'instructions' => 'Enter the benefit text.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
        ),
    ),
    'min' => '',
    'max' => '',
),



					'layout_6672f432253d2' => array(
						'key' => 'layout_6672f432253d2',
						'name' => 'image',
						'label' => 'Image',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_6672f439253d4',
								'label' => 'Image Source',
								'name' => 'image_source',
								'aria-label' => '',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'upload' => 'Upload',
									'url' => 'URL',
								),
								'default_value' => '',
								'return_format' => 'value',
								'allow_null' => 0,
								'other_choice' => 0,
								'layout' => 'vertical',
								'save_other_choice' => 0,
							),
							array(
								'key' => 'field_6672f47c253d5',
								'label' => 'Image Upload',
								'name' => 'image_upload',
								'aria-label' => '',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_6672f439253d4',
											'operator' => '==',
											'value' => 'upload',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
								'preview_size' => 'medium',
							),
							array(
								'key' => 'field_6672f4a7253d6',
								'label' => 'Image URL',
								'name' => 'image_url',
								'aria-label' => '',
								'type' => 'url',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_6672f439253d4',
											'operator' => '==',
											'value' => 'url',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
				),

				'min' => '',
				'max' => '',
				'button_label' => 'Add Module',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),

			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),

			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));
});

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
		'key' => 'group_6685d78a401b6',
		'title' => 'Ekipet',
		'fields' => array(
			array(
				'key' => 'field_6685d78a4d18d',
				'label' => 'Name Team',
				'name' => 'name_team',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_6685dad124dd3',
				'label' => 'Description',
				'name' => 'description',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_6685d8f0a4f4e',
				'label' => 'Select Members',
				'name' => 'select_members',
				'aria-label' => '',
				'type' => 'user', // Change this to 'user'
				'instructions' => 'Select team members',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'role' => '', // Optional: specify user roles to display
				'allow_null' => 1,
				'multiple' => 1, // Allow selecting multiple users
				'return_format' => 'object', // You can use 'array' or 'id' based on your preference
			),
			array(
				'key' => 'field_668d03122ba39',
				'label' => 'Email',
				'name' => 'email',
				'aria-label' => '',
				'type' => 'email',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_668d0a0a32678',
				'label' => 'Project',
				'name' => 'project',
				'aria-label' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'projects',
				),
				'post_status' => '',
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
					1 => 'post_type',
					2 => 'taxonomy',
				),
				'return_format' => 'object',
				'min' => '',
				'max' => '',
				'elements' => '',
				'bidirectional' => 0,
				'bidirectional_target' => array(
				),
			),
			array(
				'key' => 'field_668d111cb0a85',
				'label' => 'Team Image',
				'name' => 'team_image',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_668d2308240c0',
				'label' => 'Leader Image',
				'name' => 'leader_image',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'preview_size' => 'medium',
			),
			array(
                'key' => 'field_668e2bafa6133',
                'label' => 'Team Leader',
                'name' => 'team_leader',
                'type' => 'user',
                'return_format' => 'object',
            ),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'teams',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );
	
	acf_add_local_field_group( array(
		'key' => 'group_6683c90b13cab',
		'title' => 'Projects',
		'fields' => array(
			array(
				'key' => 'field_6683c90b36db5',
				'label' => 'Name Project',
				'name' => 'name_project',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_668673c3c88ed',
				'label' => 'Description',
				'name' => 'description',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'projects',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );
} );


add_action('acf/include_fields', function () {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group(array(
        'key' => 'group_user_profile_fields',
        'title' => 'User Profile Fields',
        'fields' => array(
            array(
                'key' => 'field_full_name',
                'label' => 'Full Name',
                'name' => 'full_name',
                'type' => 'text',
                'required' => 1,
            ),
            array(
                'key' => 'field_email',
                'label' => 'Email',
                'name' => 'email',
                'type' => 'email',
                'required' => 1,
            ),
            array(
                'key' => 'field_phone',
                'label' => 'Phone',
                'name' => 'phone',
                'type' => 'text',
                'required' => 1,
            ),
            array(
                'key' => 'field_address',
                'label' => 'Address',
                'name' => 'address',
                'type' => 'text',
            ),
            array(
                'key' => 'field_position',
                'label' => 'Role in Company',
                'name' => 'role',
                'type' => 'text',
            ),
            array(
                'key' => 'field_user_picture',
                'label' => 'User Picture',
                'name' => 'user_picture',
                'type' => 'image',
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
            ),
            array(
                'key' => 'field_experience',
                'label' => 'Experience',
                'name' => 'experience',
                'type' => 'text',
            ),
            array(
                'key' => 'field_age',
                'label' => 'Age',
                'name' => 'age',
                'type' => 'text',
            ),
            
            array(
                'key' => 'field_gender',
                'label' => 'Gender',
                'name' => 'gender',
                'type' => 'text',
            ),
            array(
                'key' => 'field_language',
                'label' => 'Language',
                'name' => 'language',
                'type' => 'text',
            ),
            array(
                'key' => 'field_education_level',
                'label' => 'Education Level',
                'name' => 'education_level',
                'type' => 'text',
            ),
			array(
                'key' => 'field_about',
                'label' => 'About',
                'name' => 'about',
                'type' => 'wysiwyg',
            ),
			array(
                'key' => 'field_member_since',
                'label' => 'Member Since',
                'name' => 'member_since',
                'type' => 'date_picker',
                'display_format' => 'F j, Y',
                'return_format' => 'F j, Y',
            ),
			array(
                'key' => 'field_user_tags',
                'label' => 'User Skills',
                'name' => 'user_tags',
                'type' => 'text',
                'instructions' => 'Enter tags separated by commas.',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'user_form',
                    'operator' => '==',
                    'value' => 'all',
                ),
            ),
        ),
    ));
});

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_66a0c83debaed',
	'title' => 'Resource Fields',
	'fields' => array(
		array(
			'key' => 'field_66a0c8fd48c8a',
			'label' => 'Resource Type',
			'name' => 'resource_type',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'file' => 'File',
				'link' => 'Link',
			),
			'default_value' => '',
			'return_format' => 'value',
			'allow_null' => 0,
			'other_choice' => 0,
			'layout' => 'vertical',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_66a0c83e671c8',
			'label' => 'Resource File',
			'name' => 'resource_file',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66a0c8fd48c8a',
						'operator' => '==',
						'value' => 'file',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'txt,pdf,doc,docx,html,xml',
		),
		array(
			'key' => 'field_66a0c85a671c9',
			'label' => 'Resource Link',
			'name' => 'resource_link',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66a0c8fd48c8a',
						'operator' => '==',
						'value' => 'link',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'resources',
			),
		),
	),
    
	
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
		'key' => 'group_66a4e799d4d18',
		'title' => 'Planings',
		'fields' => array(
			array(
				'key' => 'field_66a4e7993e455',
				'label' => 'Planing',
				'name' => 'planing',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_66a4e7b43e456',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_66a4e7993e455',
					),
					array(
						'key' => 'field_66a4e7d13e457',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
						'parent_repeater' => 'field_66a4e7993e455',
					),
					array(
						'key' => 'field_66a4e7df3e458',
						'label' => 'Schedule title',
						'name' => 'schedule_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_66a4e7993e455',
					),
					array(
						'key' => 'field_66a4e7fe3e459',
						'label' => 'Schedule time',
						'name' => 'schedule_time_',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_66a4e7993e455',
					),
					array(
						'key' => 'field_66a4e8a3e460',
						'label' => 'Icon',
						'name' => 'icon',
						'type' => 'image',
						'instructions' => 'Upload an icon for this planning.',
						'required' => 0,
						'return_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),

				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'plannings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );
} );

add_action( 'acf/include_fields', function() {
    if ( ! function_exists( 'acf_add_local_field_group' ) ) {
        return;
    }

    acf_add_local_field_group( array(
        'key' => 'group_products_fields',
        'title' => 'Products Fields',
        'fields' => array(
            array(
                'key' => 'field_product_thumbnail',
                'label' => 'Product Thumbnail',
                'name' => 'product_thumbnail',
                'type' => 'image',
                'instructions' => 'Upload a thumbnail image for the product.',
                'required' => 0,
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
            ),
            array(
                'key' => 'field_product_excerpt',
                'label' => 'Product Excerpt',
                'name' => 'product_excerpt',
                'type' => 'textarea',
                'instructions' => 'Enter a short description or excerpt for the product.',
                'required' => 0,
                'new_lines' => 'wpautop',
                'maxlength' => '',
                'rows' => 3,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'products',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
});

add_action( 'acf/include_fields', function() {
    if ( ! function_exists( 'acf_add_local_field_group' ) ) {
        return;
    }

    acf_add_local_field_group(array(
		'key' => 'group_tech_support',
		'title' => 'Tech Support',
		'fields' => array(
			array(
				'key' => 'field_icon',
				'label' => 'Icon',
				'name' => 'icon',
				'type' => 'image',
				'return_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array(
				'key' => 'field_sub_title',
				'label' => 'Sub Title',
				'name' => 'sub_title',
				'type' => 'text',
			),
			array(
				'key' => 'field_description',
				'label' => 'Description',
				'name' => 'description',
				'type' => 'textarea',
			),
			array(
				'key' => 'field_bullet_points',
				'label' => 'Bullet Points',
				'name' => 'bullet_points',
				'type' => 'repeater',
				'sub_fields' => array(
					array(
						'key' => 'field_bullet_point',
						'label' => 'Bullet Point',
						'name' => 'bullet_point',
						'type' => 'text',
					),
				),
				'min' => 1,
				'layout' => 'table',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'tech-support',
				),
			),
		),
		'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
	));
});

	
